hardcoreeng/platform

common/changes/@anticrm/query/feature-make--query--tests_2021-06-01-10-40.json, common/scripts/coverage.sh, packages/query/src/__tests__/model.tx.json, packages/query/src/__tests__/query.test.ts, packages/query/tsconfig.json
Fixes #10 
Signed-off-by: Denis Bykhov <bykhov.denis@gmail.com>
=> Query test

common/changes/@anticrm/core/storage-classes_2021-06-01-13-36.json, common/changes/@anticrm/plugin-core-dev/storage-classes_2021-06-01-13-36.json, common/changes/@anticrm/query/storage-classes_2021-06-01-13-36.json, packages/core/src/__tests__/memdb.test.ts, packages/core/src/client.ts, packages/core/src/memdb.ts, packages/core/src/storage.ts, packages/query/src/__tests__/query.test.ts, packages/query/src/index.ts, plugins/plugin-core-dev/src/connection.ts, plugins/plugin-core-dev/src/index.ts
Storages such as `MemDb` and `LiveQuery` now implemented with classes.
=> Storage implementations now classes

common/changes/@anticrm/chunter-assets/chunter-task-l10n_2021-06-01-16-04.json, common/changes/@anticrm/chunter-impl/chunter-task-l10n_2021-06-01-16-04.json, common/changes/@anticrm/task-assets/chunter-task-l10n_2021-06-01-16-04.json, common/changes/@anticrm/task-impl/chunter-task-l10n_2021-06-01-16-04.json, common/changes/@anticrm/ui/chunter-task-l10n_2021-06-01-16-04.json, packages/ui/src/components/TreeNode.svelte, packages/ui/src/components/internal/TreeElement.svelte, plugins/chunter-assets/lang/en.json, plugins/chunter-assets/src/index.ts, plugins/chunter-impl/src/components/Navigator.svelte, plugins/chunter-impl/src/plugin.ts, plugins/task-assets/lang/en.json, plugins/task-assets/src/index.ts, plugins/task-impl/src/components/Navigator.svelte, plugins/task-impl/src/plugin.ts
Signed-off-by: Andrey Platov <andrey.v.platov@gmail.com>
=> Add localized strings to `chunter` and `task`

common/changes/@anticrm/theme/toggle-comp_2021-06-01-17-44.json, common/changes/@anticrm/ui/toggle-comp_2021-06-01-17-44.json, common/changes/@anticrm/workbench-impl/toggle-comp_2021-06-01-17-44.json, packages/theme/styles/_colors.scss, packages/ui/src/components/Button.svelte, packages/ui/src/components/EditBox.svelte, packages/ui/src/components/StatusControl.svelte, packages/ui/src/components/Toggle.svelte, packages/ui/src/index.ts, plugins/workbench-impl/src/components/AppItem.svelte, plugins/workbench-impl/src/components/CreateChannel.svelte, plugins/workbench-impl/src/components/Workbench.svelte
Fixes #19 
Signed-off-by: Alexander Platov <sas_lord@mail.ru>
=> Add `Toggle`, `CreateChannel`, fix colors

common/changes/@anticrm/core/feature--livequery--does-not-match-queri_2021-06-02-10-45.json, common/changes/@anticrm/core/feature--livequery--does-not-match-queri_2021-06-02-12-04.json, common/changes/@anticrm/plugin-core-dev/feature--livequery--does-not-match-queri_2021-06-02-10-45.json, common/changes/@anticrm/plugin-core-dev/feature--livequery--does-not-match-queri_2021-06-02-12-04.json, common/changes/@anticrm/query/feature--livequery--does-not-match-queri_2021-06-01-16-23.json, common/changes/@anticrm/query/feature--livequery--does-not-match-queri_2021-06-02-10-45.json, common/changes/@anticrm/query/feature--livequery--does-not-match-queri_2021-06-02-12-04.json, common/changes/@anticrm/query/feature--livequery--does-not-match-queri_2021-06-02-12-38.json, packages/core/src/client.ts, packages/core/src/hierarchy.ts, packages/core/src/memdb.ts, packages/core/src/storage.ts, packages/query/jest.config.js, packages/query/src/__tests__/query.test.ts, packages/query/src/index.ts, plugins/plugin-core-dev/src/connection.ts
=> LiveQuery does not match queries correctly

common/changes/@anticrm/platform/feature-invalid--label--for--editbox--re_2021-06-02-05-21.json, common/changes/@anticrm/platform/feature-invalid--label--for--editbox--re_2021-06-02-09-37.json, packages/platform/src/__tests__/i18n.test.ts, packages/platform/src/i18n.ts
Fixes #4 
Signed-off-by: Denis Bykhov <bykhov.denis@gmail.com>
=> Fixed get translation when incorrect string

.github/workflows/main.yml, common/changes/@anticrm/chunter-assets/update-deps_2021-06-03-11-53.json, common/changes/@anticrm/chunter-impl/update-deps_2021-06-03-11-53.json, common/changes/@anticrm/task-assets/update-deps_2021-06-03-11-53.json, common/changes/@anticrm/task-impl/update-deps_2021-06-03-11-53.json, common/changes/@anticrm/workbench/update-deps_2021-06-03-11-53.json, common/config/rush/pnpm-lock.yaml, plugins/chunter-assets/package.json, plugins/chunter-impl/package.json, plugins/task-assets/package.json, plugins/task-impl/package.json, plugins/workbench/package.json
=> Add `rush` dependencies check

common/changes/@anticrm/ui/fix-dialog_2021-06-05-09-32.json, packages/ui/src/components/Dialog.svelte, packages/ui/src/components/internal/Modal.svelte
Fixes #52 
Signed-off-by: Alexander Platov <sas_lord@mail.ru>
=> Fix shadow in `Dialog`

.github/workflows/main.yml, common/scripts/coverage.sh, packages/model/jest.config.js, packages/model/src/__tests__/dsl.test.ts, packages/model/src/dsl.ts
Signed-off-by: Andrey Platov <andrey.v.platov@gmail.com>
=> fixes Fix `model` tests #61, add more tests to CI

common/changes/@anticrm/chunter-impl/layout-create_2021-06-09-10-10.json, common/changes/@anticrm/workbench-impl/layout-create_2021-06-09-10-10.json, plugins/chunter-impl/src/components/CreateChannel.svelte, plugins/workbench-impl/src/components/Chat.svelte, plugins/workbench-impl/src/components/Workbench.svelte
Fixes #66 
Signed-off-by: Alexander Platov <sas_lord@mail.ru>
=> Fix layout `Chat` and `Create Channel`

common/changes/@anticrm/core/fix-75_2021-06-09-17-27.json, common/scripts/each-diff.sh, models/core/src/__gen-model.ts, models/core/src/component.ts, models/core/src/core.ts, models/core/src/index.ts, models/core/src/tx.ts, models/core/src/vdoc.ts, packages/core/src/__tests__/vdocdb.test.ts, packages/core/src/component.ts, packages/core/src/tx.ts, packages/core/src/vdoc.ts, packages/core/tsconfig.json, packages/model/src/__tests__/dsl.test.ts, packages/model/src/component.ts, packages/model/src/dsl.ts, packages/model/src/index.ts
1. Unify VDoc ops into Ops
2. Fix each-diff script.
Closes #75
=> Unify VDoc ops into Ops

common/changes/@anticrm/core/create-doc-return-doc_2021-06-14-08-04.json, packages/core/src/tx.ts
Allow TxOperations.createDoc to return doc
=> Allow TxOperations.createDoc to return doc

.github/workflows/main.yml, common/changes/@anticrm/mongo-storage/mongo-storage_2021-06-14-10-22.json, common/changes/@anticrm/plugin-core-impl/mongo-storage_2021-06-14-10-22.json, common/changes/@anticrm/server/mongo-storage_2021-06-14-10-22.json, common/config/rush/pnpm-lock.yaml, plugins/plugin-core-impl/package.json, rush.json, server/mongo-storage/.eslintrc.js, server/mongo-storage/api-extractor.json, server/mongo-storage/jest.config.js, server/mongo-storage/package.json, server/mongo-storage/src/__tests__/storage.test.ts, server/mongo-storage/src/__tests__/tasks.ts, server/mongo-storage/src/collection.ts, server/mongo-storage/src/component.ts, server/mongo-storage/src/dispatcher.ts, server/mongo-storage/src/domainFilter.ts, server/mongo-storage/src/index.ts, server/mongo-storage/src/query.ts, server/mongo-storage/src/storage.ts, server/mongo-storage/src/tx.ts, server/mongo-storage/tsconfig.json
=> Mongo Storage

models/all/package.json, models/all/src/genmodel.ts, models/all/src/index.ts
Allow model all builder to be imported
=> Allow model all builder to be imported

common/changes/@anticrm/core/predicate_2021-06-23-07-03.json, packages/core/src/memdb.ts, packages/core/src/predicate.ts
This is not good yet and shall be developed further.
=> Initial predicate implementation

common/changes/@anticrm/core/fix-server-complexity_2021-06-24-14-39.json, common/changes/@anticrm/node-client/fix-server-complexity_2021-06-24-14-39.json, common/changes/@anticrm/server/fix-server-complexity_2021-06-24-14-39.json, common/changes/@anticrm/workspace/fix-server-complexity_2021-06-24-14-39.json, common/config/rush/pnpm-lock.yaml, packages/core/src/client.ts, packages/core/src/predicate.ts, server/client/src/connection.ts, server/client/src/index.ts, server/server/package.json, server/server/src/__tests__/client.ts, server/server/src/__tests__/server.test.ts, server/server/src/security.ts, server/server/src/server.ts, server/server/src/workspaces.ts, server/workspace/src/index.ts, server/workspace/src/storage.ts, tests/server/src/workspace.test.ts
Reduce complexity of server and add more tests
=> Reduce Server complexity

common/changes/@anticrm/elastic/elastic-push_2021-06-25-07-50.json, server/elastic/src/__tests__/core.tx.json, server/elastic/src/__tests__/elasticStorage.test.ts, server/elastic/src/index.ts
Changed ES 'update' request to script logic, it works but seems strange and I'm not sure about performance
=> Elastic push

common/changes/@anticrm/core/remove-support_2021-06-30-12-49.json, common/changes/@anticrm/mongo/remove-support_2021-06-30-12-49.json, models/core/src/tx.ts, packages/core/src/__tests__/memdb.test.ts, packages/core/src/component.ts, packages/core/src/memdb.ts, packages/core/src/tx.ts, server/mongo/src/__tests__/storage.test.ts, server/mongo/src/storage.ts
=> Allow to remove documents

common/changes/@anticrm/server/server-model_2021-07-01-09-23.json, common/changes/@anticrm/workspace/server-model_2021-07-01-09-23.json, server/server/src/workspaces.ts, server/workspace/src/__tests__/workspace.test.ts, server/workspace/src/index.ts
Server supported ModelDb instance
I twill be used by security and derived data.
=> Server supported ModelDb instance

common/changes/@anticrm/elastic/feature-delete-on-elastic_2021-07-02-04-16.json, server/elastic/src/__tests__/elasticStorage.test.ts, server/elastic/src/index.ts
Implemented txDeleteDoc for elastic
close #159
=> Delete on elastic

common/changes/@anticrm/server/feature-security-use-model_2021-07-02-13-00.json, common/changes/@anticrm/workspace/feature-security-use-model_2021-07-05-05-49.json, server/server/src/__tests__/security.test.ts, server/server/src/security.ts, server/server/src/workspaces.ts, server/workspace/src/__tests__/workspace.test.ts, server/workspace/src/index.ts
=> Security use model

common/changes/@anticrm/query/fix-185_2021-07-09-06-36.json, packages/query/src/__tests__/query.test.ts, packages/query/src/index.ts
Fix Live query unsubscribe
Closes #185
=> Fix Live query unsubscribe

common/changes/@anticrm/plugin-core-impl/fix-189_2021-07-09-07-22.json, common/changes/@anticrm/plugin-core/fix-189_2021-07-09-07-22.json, plugins/plugin-core-impl/src/index.ts, plugins/plugin-core/src/index.ts
=> Fix #189: Plugin core proper Client interface

common/changes/@anticrm/text/fix-187_2021-07-09-06-57.json, packages/text/src/__tests__/textmodel.test.ts, packages/text/src/serializer.ts
=> Fix 187: Text wrong serialize headers

common/changes/@anticrm/chunter-impl/random-dev-data_2021-07-12-05-37.json, common/changes/@anticrm/chunter/random-dev-data_2021-07-12-05-37.json, common/changes/@anticrm/core/random-dev-data_2021-07-12-05-37.json, common/changes/@anticrm/plugin-core-dev/random-dev-data_2021-07-12-05-37.json, common/config/rush/pnpm-lock.yaml, models/dev/.eslintrc.js, models/dev/api-extractor.json, models/dev/jest.config.js, models/dev/package.json, models/dev/src/demoChunter.ts, models/dev/src/demoTask.ts, models/dev/src/genmodel.ts, models/dev/src/index.ts, models/dev/tsconfig.json, packages/core/src/__tests__/client.test.ts, packages/core/src/hierarchy.ts, packages/core/src/memdb.ts, packages/core/src/shortref.ts, packages/model/src/dsl.ts, plugins/chunter-impl/src/components/Channel.svelte, plugins/chunter/src/index.ts, plugins/plugin-core-dev/package.json, plugins/plugin-core-dev/src/__tests__/client.test.ts, plugins/plugin-core-dev/src/connection.ts, rush.json
=> Random Dev data generation

common/changes/@anticrm/chunter-impl/fix-202_2021-07-12-11-34.json, common/changes/@anticrm/richeditor/fix-202_2021-07-12-11-34.json, packages/richeditor/src/MessageEditor.svelte, packages/richeditor/src/__test__/message-editor.test.ts, packages/richeditor/src/index.ts, packages/richeditor/src/transform.ts, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/chunter-impl/src/components/refinput/CompletionPopup.svelte, plugins/chunter-impl/src/components/refinput/CompletionPopupHelper.ts
Chunter input with reference title search
Closes #202
=> Chunter input with reference title search

common/changes/@anticrm/task-impl/task-kanban_2021-07-12-05-44.json, common/changes/@anticrm/task/task-kanban_2021-07-12-05-44.json, models/dev/src/demoTask.ts, models/task/src/index.ts, plugins/task-impl/src/components/CreateTask.svelte, plugins/task-impl/src/components/KanbanCard.svelte, plugins/task-impl/src/components/KanbanPanel.svelte, plugins/task-impl/src/components/KanbanView.svelte, plugins/task-impl/src/components/TableView.svelte, plugins/task-impl/src/components/TaskView.svelte, plugins/task-impl/src/index.ts, plugins/task-impl/src/plugin.ts, plugins/task/src/index.ts
=> Task kanban

.github/workflows/main.yml
Show git diff after formatting is applied.
=> Show git diff after formatting is applied.

.github/workflows/main.yml, common/changes/@anticrm/chunter-impl/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/chunter/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/core/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/plugin-core-dev/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/plugin-core-impl/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/query/fix-227_2021-07-21-08-33.json, common/changes/@anticrm/ui/fix-227_2021-07-21-08-33.json, common/config/rush/pnpm-lock.yaml, models/chunter/src/index.ts, models/dev/src/demoChunter.ts, packages/core/package.json, packages/core/src/__tests__/derived.test.ts, packages/core/src/derived/index.ts, packages/core/src/derived/processor.ts, packages/core/src/derived/utils.ts, packages/core/src/operator.ts, packages/query/src/index.ts, packages/ui/src/index.ts, plugins/chunter-impl/src/components/ChannelView.svelte, plugins/chunter-impl/src/components/Comments.svelte, plugins/chunter-impl/src/components/Message.svelte, plugins/chunter-impl/src/components/ThreadsView.svelte, plugins/chunter-impl/src/index.ts, plugins/chunter-impl/src/plugin.ts, plugins/chunter/src/index.ts, plugins/plugin-core-dev/package.json, plugins/plugin-core-dev/src/connection.ts, plugins/plugin-core-dev/src/index.ts, plugins/plugin-core-impl/src/index.ts
1. Chunter Threads support
2. Add DD collection allow to map objects
3. Fix LiveQuery update for dev and server modes
4. Fix DD for dev handled multiple times.
Close #227 
=> Chunter Threads support

common/changes/@anticrm/chunter-impl/thread_header_fix_2021-07-28-08-16.json, plugins/chunter-impl/src/components/Message.svelte
Update header in thread when changed selected message
=> Thread header fix

common/changes/@anticrm/chunter-impl/derived-data-fix_2021-07-27-14-04.json, common/changes/@anticrm/chunter/derived-data-fix_2021-07-27-14-04.json, common/changes/@anticrm/core/derived-data-fix_2021-07-27-14-04.json, common/changes/@anticrm/plugin-core-dev/derived-data-fix_2021-07-28-07-22.json, common/changes/@anticrm/query/derived-data-fix_2021-07-27-14-04.json, common/changes/@anticrm/server/derived-data-fix_2021-07-28-07-22.json, common/changes/@anticrm/task-impl/derived-data-fix_2021-07-27-14-04.json, common/config/rush/pnpm-lock.yaml, models/chunter/src/index.ts, models/dev/src/demoChunter.ts, models/dev/src/demoTask.ts, packages/core/src/__tests__/derived.test.ts, packages/core/src/classes.ts, packages/core/src/client.ts, packages/core/src/derived/processor.ts, packages/core/src/memdb.ts, packages/core/src/utils.ts, packages/query/package.json, packages/query/src/__tests__/query.test.ts, packages/query/src/index.ts, plugins/chunter-impl/src/components/Comments.svelte, plugins/chunter-impl/src/components/ThreadsView.svelte, plugins/chunter/src/index.ts, plugins/plugin-core-dev/src/__tests__/client.test.ts, plugins/plugin-core-dev/src/connection.ts, plugins/plugin-core-dev/src/index.ts, plugins/task-impl/src/components/CommentsView.svelte, plugins/task-impl/src/components/CreateTask.svelte, server/server/src/__tests__/client.server.test.ts
Fixed multiple update tx, implemented fullRef with _class
=> Derived data fix

common/changes/@anticrm/accounts/separate-accountId_2021-08-14-10-22.json, common/changes/@anticrm/chunter-impl/separate-accountId_2021-08-14-10-22.json, common/changes/@anticrm/core/separate-accountId_2021-08-14-10-22.json, common/changes/@anticrm/server/separate-accountId_2021-08-14-10-22.json, common/changes/@anticrm/task-impl/separate-accountId_2021-08-14-10-22.json, common/changes/@anticrm/ui/separate-accountId_2021-08-14-10-22.json, dev/server/src/index.ts, models/core/src/security.ts, models/dev/src/demoAccount.ts, packages/core/src/__tests__/memdb.test.ts, packages/core/src/classes.ts, packages/core/src/minmodel/index.ts, packages/core/src/query.ts, packages/ui/src/components/UserBox.svelte, packages/ui/src/components/UserInfo.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/task-impl/src/components/EditTask.svelte, server/accounts/src/__tests__/accounts.test.ts, server/accounts/src/index.ts, server/server/src/__tests__/client.server.test.ts, server/server/src/server.ts, server/server/src/token.ts, server/server/src/wsserver.ts
1. Use accountId generated with account host, it should be uniq.
2. Add email to Account 
3. Some small fixes related to it.
=> Separate account

common/changes/@anticrm/chunter-assets/direct-messages_2021-08-18-11-47.json, common/changes/@anticrm/chunter-impl/direct-messages_2021-08-18-11-47.json, common/changes/@anticrm/chunter/direct-messages_2021-08-18-11-47.json, common/changes/@anticrm/workbench-impl/direct-messages_2021-08-18-11-47.json, common/changes/@anticrm/workbench/direct-messages_2021-08-18-11-47.json, common/config/rush/pnpm-lock.yaml, models/chunter/src/index.ts, models/chunter/src/plugin.ts, models/dev/src/demoChunter.ts, plugins/chunter-assets/lang/en.json, plugins/chunter-impl/package.json, plugins/chunter-impl/src/components/CreateChannel.svelte, plugins/chunter-impl/src/components/CreateDirectMessage.svelte, plugins/chunter-impl/src/index.ts, plugins/chunter-impl/src/plugin.ts, plugins/chunter/src/index.ts, plugins/workbench-impl/package.json, plugins/workbench-impl/src/components/NavHeader.svelte, plugins/workbench-impl/src/components/Navigator.svelte, plugins/workbench-impl/src/components/Spaces.svelte, plugins/workbench-impl/src/components/Workbench.svelte, plugins/workbench-impl/src/components/navigator/SpacesNav.svelte, plugins/workbench-impl/src/components/navigator/SpecialElement.svelte, plugins/workbench-impl/src/components/navigator/TreeElement.svelte, plugins/workbench/src/index.ts
1. Direct messages in chunter
2. Some changes in workbench to allow some special cases in navigation.
=> Direct messages

common/changes/@anticrm/core/fix-282_2021-08-20-12-29.json, common/changes/@anticrm/server/fix-282_2021-08-20-12-29.json, common/changes/@anticrm/workspace/fix-282_2021-08-20-12-29.json, packages/core/src/derived/descriptors.ts, packages/core/src/derived/index.ts, packages/core/src/derived/processor.ts, server/server/src/__tests__/security.test.ts, server/server/src/security.ts, server/server/src/workspaces.ts, server/server/src/wsserver.ts, server/workspace/src/__tests__/workspace.test.ts, server/workspace/src/index.ts
Fix #282 Filter server send transactions by clientId
=> Fix #282 Filter server send transactions by clientId

common/changes/@anticrm/chunter-impl/spaces-dialog_2021-08-23-13-49.json, common/changes/@anticrm/task-impl/spaces-dialog_2021-08-23-13-49.json, common/changes/@anticrm/ui/spaces-dialog_2021-08-23-13-49.json, common/changes/@anticrm/workbench-impl/spaces-dialog_2021-08-23-13-49.json, packages/ui/src/components/Dialog.svelte, packages/ui/src/components/Splitter.svelte, packages/ui/src/index.ts, plugins/chunter-impl/src/components/Channel.svelte, plugins/task-impl/src/components/Comments.svelte, plugins/workbench-impl/src/components/Workbench.svelte
(Fixes #289)
Signed-off-by: Alexander Platov <sas_lord@mail.ru>
=> Dialog margins and Slitter component

common/changes/@anticrm/query/query-fixs_2021-08-25-08-54.json, packages/query/src/__tests__/query.test.ts, packages/query/src/index.ts
Minor query fixes & additional tests
=> Query fixs

common/changes/@anticrm/core/allow-dd-over-dd_2021-09-03-09-23.json, packages/core/src/__tests__/derived.test.ts, packages/core/src/derived/processor.ts
Allow Derived data from Derived data
=> Derived data from Derived data should be supported

common/changes/@anticrm/core/upgradable-model_2021-09-03-08-48.json, common/changes/@anticrm/model-recruiting/upgradable-model_2021-09-03-08-48.json, common/changes/@anticrm/workbench-impl/upgradable-model_2021-09-03-08-48.json, common/changes/@anticrm/workspaces/upgradable-model_2021-09-03-08-48.json, common/config/rush/pnpm-lock.yaml, models/chunter/src/index.ts, models/chunter/src/plugin.ts, models/dev/src/demoAccount.ts, models/dev/src/demoChunter.ts, models/dev/src/demoTask.ts, models/meeting/src/index.ts, models/meeting/src/plugin.ts, models/recruiting/package.json, models/recruiting/src/index.ts, models/recruiting/src/plugin.ts, models/task/src/index.ts, models/task/src/plugin.ts, packages/core/src/__tests__/model.diff.test.ts, packages/core/src/component.ts, packages/core/src/minmodel/index.ts, packages/core/src/model.ts, packages/model/src/component.ts, plugins/plugin-core-dev/package.json, plugins/workbench-impl/src/components/WorkbenchApp.svelte, server/workspaces/package.json, server/workspaces/src/index.ts
1. Method to calculate an minimal update from previous model state to new model state.
2. Some Id fixes for model instances, to perform update instead of replace.
3. Update to dev model generation, to have stable Ids, for more smooth dev experience.
=> Upgradable model

common/changes/@anticrm/core/no-tx-dd_2021-09-06-05-44.json, common/changes/@anticrm/workspace/no-tx-dd_2021-09-06-05-44.json, package.json, packages/core/src/tx.ts, server/workspace/src/storage.ts
No Tx should be stored for DD object operations
=> No Tx should be stored for DD object operations

common/changes/@anticrm/ui/router-prefix-quickfix_2021-09-07-05-16.json, packages/ui/src/router.ts
=> Router prefix check quick fix

dev/prod/build_demo.sh
=> Fix Github demo redirect

common/changes/@anticrm/chunter-impl/fix-reference-send_2021-09-08-15-20.json, common/changes/@anticrm/task-impl/fix-reference-send_2021-09-08-15-20.json, common/changes/@anticrm/ui/fix-reference-send_2021-09-08-15-20.json, packages/ui/src/components/text/MessageViewer.svelte, plugins/chunter-impl/src/components/ChannelView.svelte, plugins/chunter-impl/src/components/CreateDirectMessage.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/chunter-impl/src/components/ThreadsView.svelte, plugins/task-impl/src/components/Comments.svelte
=> Fix Send button

common/changes/@anticrm/chunter-impl/id_ne_fix_2021-09-14-03-00.json, common/changes/@anticrm/core/id_ne_fix_2021-09-14-03-00.json, packages/core/src/query.ts, plugins/chunter-impl/src/components/CreateDirectMessage.svelte
=> _Id $ne fix

common/changes/@anticrm/chunter-impl/name_instead_email_2021-09-20-13-34.json, common/changes/@anticrm/task-impl/name_instead_email_2021-09-20-13-34.json, common/changes/@anticrm/ui/name_instead_email_2021-09-20-13-34.json, packages/ui/src/components/UserBox.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/task-impl/src/components/DescriptionEditor.svelte, plugins/task-impl/src/components/EditTask.svelte
close #366  close #359  close #362
=> Minor fixes

common/changes/@anticrm/workbench-impl/spacesNav_fix_2021-09-21-03-29.json, plugins/workbench-impl/src/components/Navigator.svelte, plugins/workbench-impl/src/components/Workbench.svelte, plugins/workbench-impl/src/components/navigator/SpacesNav.svelte
=> SpacesNav notifications fix

common/changes/@anticrm/plugin-core-impl/notification_mapper_fix_2021-09-27-13-08.json, plugins/plugin-core-dev/package.json, plugins/plugin-core-dev/src/index.ts, plugins/plugin-core-impl/package.json, plugins/plugin-core-impl/src/index.ts
=> Notification mapper fix

common/changes/@anticrm/core/dd-recreate_2021-09-27-15-06.json, common/changes/@anticrm/mongo/dd-recreate_2021-09-27-15-06.json, common/changes/@anticrm/server/dd-recreate_2021-09-27-15-12.json, common/changes/@anticrm/status/dd-recreate_2021-09-27-15-06.json, common/changes/@anticrm/ui/dd-recreate_2021-09-27-15-06.json, common/changes/@anticrm/workspaces/dd-recreate_2021-09-27-16-03.json, models/core/src/component.ts, models/core/src/derived.ts, models/core/src/index.ts, packages/core/src/__tests__/connection.ts, packages/core/src/__tests__/derived.test.ts, packages/core/src/__tests__/memdb.test.ts, packages/core/src/__tests__/model.diff.test.ts, packages/core/src/component.ts, packages/core/src/derived/index.ts, packages/core/src/derived/processor.ts, packages/core/src/memdb.ts, packages/core/src/minmodel/index.ts, packages/core/src/model.ts, packages/core/src/storage.ts, packages/status/src/index.ts, packages/ui/src/components/Component.svelte, server/mongo/src/__tests__/storage.test.ts, server/mongo/src/storage.ts, server/mongo/src/tx.ts, server/server/src/workspaces.ts, server/server/src/wsserver.ts, server/workspaces/src/index.ts
1. Allow to refresh DD on server startup
2. Introduce skip for FindOptions
Closes #337 
Closes #165
=> Derived Data Recreation

common/changes/@anticrm/chunter-assets/chunter-fixes-01_2021-09-27-17-54.json, common/changes/@anticrm/chunter-impl/chunter-fixes-01_2021-09-27-17-54.json, common/changes/@anticrm/chunter/chunter-fixes-01_2021-09-27-17-54.json, common/changes/@anticrm/ui/chunter-fixes-01_2021-09-27-17-54.json, common/changes/@anticrm/workbench-impl/chunter-fixes-01_2021-09-27-17-54.json, packages/ui/src/components/internal/Root.svelte, plugins/chunter-assets/lang/en.json, plugins/chunter-impl/src/components/ChannelSeparator.svelte, plugins/chunter-impl/src/components/Message.svelte, plugins/chunter-impl/src/components/Replies.svelte, plugins/chunter-impl/src/components/SpaceItem.svelte, plugins/chunter/src/index.ts, plugins/workbench-impl/src/components/Workbench.svelte
1. Clickable replies
2. Reply only by button click.
2. Fix some messages.
4. Width fixes.
5. Remove reactions for now.
6. Fix long chunter channel name in navigator.
=> Chunter fixes

products/hr-build/package.json, products/hr-build/src/model.ts, products/hr-build/src/platform.ts
=> Fix HR Build actions

common/changes/@anticrm/richeditor/tasks_minor_fixes_2021-09-28-10-15.json, common/changes/@anticrm/task-impl/tasks_minor_fixes_2021-09-28-10-15.json, common/changes/@anticrm/text/tasks_minor_fixes_2021-09-28-10-15.json, common/changes/@anticrm/ui/tasks_minor_fixes_2021-09-28-10-15.json, packages/richeditor/src/MessageEditor.svelte, packages/text/src/parser.ts, packages/ui/src/components/CheckBoxList.svelte, packages/ui/src/components/CheckBoxWithLabel.svelte, packages/ui/src/components/UserBox.svelte, plugins/task-impl/src/components/Card.svelte, plugins/task-impl/src/components/CreateTask.svelte, plugins/task-impl/src/components/EditTask.svelte, plugins/task-impl/src/components/KanbanCard.svelte
close #388 close #387 close #383 close #380
=> Tasks minor fixes

common/changes/@anticrm/core/separate-dd-state-space_2021-09-28-08-49.json, packages/core/src/component.ts, packages/core/src/derived/processor.ts
=> Separate DD State Space

common/changes/@anticrm/status/fix-mergeIds_2021-09-29-12-00.json, common/config/rush/pnpm-lock.yaml, packages/status/package.json, packages/status/src/index.ts
=> Fix mergeIds modify source plugin

common/changes/@anticrm/chunter-impl/fix-400_2021-09-30-06-24.json, plugins/chunter-impl/src/components/ReferenceInput.svelte
=> Fix Bold/italic styles

plugins/plugin-core-dev/src/connection.ts
=> Fix derived data in core-plugin-dev

common/changes/@anticrm/chunter-assets/fix-398_2021-09-30-09-43.json, common/changes/@anticrm/chunter-impl/fix-398_2021-09-30-09-43.json, common/changes/@anticrm/chunter/fix-398_2021-09-30-09-43.json, plugins/chunter-assets/lang/en.json, plugins/chunter-impl/src/components/Message.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/chunter/src/index.ts
Allow to edit chunter messages/comments
Closes: #398
=> Allow to edit chunter messages/comments

deployments/docker-compose/docker-compose.yaml
close #416 
Signed-off-by: Denis Bykhov <bykhov.denis@gmail.com>
=> docker-compose files save

common/changes/@anticrm/s3/fix-docker-compose_2021-10-04-10-38.json, deployments/docker-compose/.env, deployments/docker-compose/docker-compose.yaml, products/hr-build/src/server.ts, server/s3/src/index.ts, server/services/src/fileServer.ts
=> Fix docker compose minio startup

common/changes/@anticrm/fsm-impl/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/fsm/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/model-fsm/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/model-recruiting/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/recruiting-impl/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/task-impl/kanban-order_2021-10-01-05-32.json, common/changes/@anticrm/ui/kanban-order_2021-10-01-05-32.json, models/fsm/src/index.ts, models/recruiting/src/index.ts, packages/ui/package.json, packages/ui/src/components/kanban/Kanban.svelte, packages/ui/src/components/kanban/Panel.svelte, packages/ui/src/components/kanban/drag.watcher.ts, packages/ui/src/components/kanban/draggable.ts, packages/ui/src/components/kanban/hoverable.ts, packages/ui/src/components/kanban/object.types.ts, packages/ui/src/components/kanban/scrollable.ts, packages/ui/src/components/kanban/utils.ts, packages/ui/src/index.ts, packages/ui/src/types.ts, plugins/fsm-impl/src/index.ts, plugins/fsm/src/index.ts, plugins/recruiting-impl/src/components/vacancies/ApplicantCard.svelte, plugins/recruiting-impl/src/components/vacancies/VacancyKanban.svelte, plugins/task-impl/src/components/KanbanView.svelte
Multiple things will be updated:
Resolves #381
=> Kanban order

README.md, common/changes/@anticrm/s3/fix-files-s3-ssl_2021-10-04-16-08.json, products/hr-build/src/server.ts, server/s3/src/__tests__/s3.test.ts, server/s3/src/index.ts
=> Fix S3 ssl for docker compose

common/changes/@anticrm/attachment-dev/multi_attachment_2021-10-05-01-53.json, common/changes/@anticrm/attachment-impl/multi_attachment_2021-10-05-01-53.json, common/changes/@anticrm/attachment/multi_attachment_2021-10-05-01-53.json, common/changes/@anticrm/ui/multi_attachment_2021-10-05-01-53.json, packages/ui/src/components/Dialog.svelte, plugins/attachment-dev/src/index.ts, plugins/attachment-impl/src/components/AddAttachment.svelte, plugins/attachment-impl/src/components/Attachment.svelte, plugins/attachment-impl/src/index.ts, plugins/attachment/src/index.ts
=> Multi attachment

common/changes/@anticrm/login-impl/event_token_2021-10-04-04-57.json, common/changes/@anticrm/plugin-core/event_token_2021-10-05-02-12.json, dev/prod/src/main.ts, plugins/login-impl/package.json, plugins/login-impl/src/index.ts, plugins/plugin-core/src/index.ts, products/hr-build/src/main.ts
=> Event token for set metadata

common/changes/@anticrm/recruiting-assets/create-applicant-initial-state_2021-10-05-09-23.json, common/changes/@anticrm/recruiting-impl/create-applicant-initial-state_2021-10-05-09-23.json, common/changes/@anticrm/recruiting/create-applicant-initial-state_2021-10-05-09-23.json, plugins/recruiting-assets/lang/en.json, plugins/recruiting-impl/src/components/vacancies/CreateApplication.svelte, plugins/recruiting/src/index.ts
=> Make possible to set applicant state on create

common/changes/@anticrm/ui/enhance-draggable_2021-10-06-01-32.json, packages/ui/src/components/kanban/draggable.ts
=> Enhance draggable

common/changes/@anticrm/chunter-impl/thread_scroll_fix_2021-10-19-03-59.json, common/changes/@anticrm/notification/thread_scroll_fix_2021-10-19-03-59.json, common/changes/@anticrm/plugin-core-impl/thread_scroll_fix_2021-10-19-03-59.json, common/changes/@anticrm/task-impl/thread_scroll_fix_2021-10-19-03-59.json, common/changes/@anticrm/workbench-impl/thread_scroll_fix_2021-10-19-03-59.json, plugins/chunter-impl/src/components/ChannelView.svelte, plugins/chunter-impl/src/components/CreateDirectMessage.svelte, plugins/chunter-impl/src/components/EmbeddedThread.svelte, plugins/chunter-impl/src/components/ThreadsView.svelte, plugins/notification/src/index.ts, plugins/plugin-core-dev/src/index.ts, plugins/plugin-core-impl/src/index.ts, plugins/task-impl/src/components/EditTask.svelte, plugins/workbench-impl/src/components/navigator/SpacesNav.svelte
=> Thread scroll fix

common/changes/@anticrm/server/fix-account-creation_2021-10-29-15-08.json, server/server/src/__tests__/client.server.test.ts, server/server/src/wsserver.ts
=> Fix account creation

common/changes/@anticrm/task-impl/table-virtualization_2021-11-01-17-45.json, common/changes/@anticrm/ui/table-virtualization_2021-11-01-17-45.json, packages/ui/src/components/Table.svelte, plugins/task-impl/src/components/TableView.svelte
=> Table virtualization

common/changes/@anticrm/chunter-impl/update-deps_2021-11-01-14-22.json, common/changes/@anticrm/core/update-deps_2021-11-01-14-22.json, common/changes/@anticrm/recruiting-impl/update-deps_2021-11-01-14-22.json, common/changes/@anticrm/richeditor/update-deps_2021-11-01-14-22.json, common/changes/@anticrm/ui/update-deps_2021-11-01-14-22.json, common/changes/@anticrm/workbench-impl/update-deps_2021-11-01-14-22.json, common/config/rush/pnpm-lock.yaml, dev/ui-build/demo/src/components/Button3.svelte, dev/ui-build/src/componentExtender.ts, dev/ui-build/src/componentParser.ts, dev/ui-build/src/componentWriter.ts, packages/core/src/storage.ts, packages/richeditor/src/index.ts, packages/ui/src/components/MDRefEditor.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte, plugins/recruiting-impl/src/components/vacancies/CreateVacancy.svelte, plugins/recruiting-impl/src/components/vacancies/VacancyEditor.svelte, plugins/workbench-impl/src/components/AppItem.svelte
1. Update all dependencies
2. Fix ui-build to produce parameters for exported functions.
3. Fix some imports inside svelte.
4.  Closes #519 - preload app tooltips.
=> Update all dependencies

common/changes/@anticrm/core/fix-ws-upgrade_2021-11-03-17-09.json, common/changes/@anticrm/workspaces/fix-ws-upgrade_2021-11-03-17-09.json, packages/core/src/derived/processor.ts, server/workspaces/src/index.ts
Fix Workspace model upgrade.
Fix DD state stored into transactions.
Closes #516
=> Fix Workspace upgrade

common/changes/@anticrm/accounts/login-fixes_2021-11-03-13-53.json, common/changes/@anticrm/login-impl/login-fixes_2021-11-03-13-53.json, common/changes/@anticrm/login/login-fixes_2021-11-03-13-53.json, common/changes/@anticrm/rpc/login-fixes_2021-11-03-13-53.json, common/changes/@anticrm/ui/login-fixes_2021-11-03-13-53.json, common/changes/@anticrm/workbench-impl/login-fixes_2021-11-03-13-53.json, dev/prod/src/main.ts, packages/rpc/src/index.ts, packages/ui/src/components/StylishEdit.svelte, plugins/login-impl/src/components/Form.svelte, plugins/login-impl/src/components/LoginForm.svelte, plugins/login-impl/src/components/SignupForm.svelte, plugins/login-impl/src/index.ts, plugins/login/src/index.ts, plugins/workbench-impl/src/components/WorkbenchApp.svelte, products/hr-build/src/main.ts, server/accounts/src/__tests__/accounts.test.ts, server/accounts/src/index.ts
1. Verify token for account exists. Closes #528
2. Fix email/password remember. Closes #338
3. Refactor login service for less complexity
=> Login fixes

common/changes/@anticrm/workbench-impl/fix-dev-login_2021-11-04-04-27.json, dev/prod/package.json, dev/prod/src/platform.ts, plugins/workbench-impl/src/components/WorkbenchApp.svelte
Fix dev mode being broken because of login
=> Fix Dev login module issues

common/changes/@anticrm/ui/any-fixes_2021-11-04-01-31.json, common/changes/@anticrm/workbench-impl/any-fixes_2021-11-04-01-31.json, packages/ui/src/components/Card.svelte, packages/ui/src/components/CheckBox.svelte, packages/ui/src/components/Panel.svelte, packages/ui/src/components/Table.svelte, plugins/workbench-impl/src/components/Workbench.svelte, plugins/workbench-impl/src/components/navigator/TreeElement.svelte
=> Update Table, CheckBox, backdrop-filter

common/changes/@anticrm/fsm-impl/fsm-order_2021-11-04-05-57.json, common/changes/@anticrm/fsm/fsm-order_2021-11-04-05-57.json, common/changes/@anticrm/model-fsm/fsm-order_2021-11-04-05-57.json, common/changes/@anticrm/recruiting-impl/fsm-order_2021-11-04-05-57.json, common/changes/@anticrm/ui/fsm-order_2021-11-04-05-57.json, common/config/rush/pnpm-lock.yaml, models/fsm/package.json, models/fsm/src/index.ts, packages/ui/src/components/kanban/Kanban.svelte, plugins/fsm-impl/package.json, plugins/fsm-impl/src/index.ts, plugins/fsm/src/index.ts, plugins/recruiting-impl/src/components/vacancies/CreateApplication.svelte, plugins/recruiting-impl/src/components/vacancies/VacancyKanban.svelte, utils/trello-importer/package.json, utils/trello-importer/src/applicant.ts, utils/trello-importer/src/fsm.ts, utils/trello-importer/src/index.ts, utils/trello-importer/src/utils.ts
=> Add rank to FSM

common/changes/@anticrm/s3/s3_test_fix_2021-11-05-08-38.json, server/s3/src/__tests__/s3.test.ts
=> S3 test fix

common/changes/@anticrm/ui/adjust-table-styles_2021-11-05-09-50.json, common/changes/@anticrm/workbench-impl/adjust-table-styles_2021-11-05-09-50.json, packages/ui/src/components/Table.svelte, plugins/workbench-impl/src/components/Workbench.svelte
=> Adjust table styles

common/changes/@anticrm/attachment-dev/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/attachment-impl/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/attachment/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/model-attachment/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/recruiting-impl/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/ui/candidate_fixes_2021-11-05-12-07.json, common/changes/@anticrm/workbench-impl/candidate_fixes_2021-11-05-12-07.json, models/attachment/src/index.ts, models/dev/src/demoAttachment.ts, packages/ui/src/components/Component.svelte, packages/ui/src/components/PopupInstance.svelte, packages/ui/src/components/Table.svelte, plugins/attachment-dev/src/index.ts, plugins/attachment-impl/src/components/Attachments.svelte, plugins/attachment-impl/src/components/AvatarEditor.svelte, plugins/attachment-impl/src/index.ts, plugins/attachment/src/index.ts, plugins/recruiting-impl/src/components/applicants/CreateApplication.svelte, plugins/recruiting-impl/src/components/candidates/CandidateApplication.svelte, plugins/recruiting-impl/src/components/candidates/CreateApplication.svelte, plugins/workbench-impl/src/components/Modal.svelte
=> Candidate fixes

common/changes/@anticrm/chunter-impl/task-ui-fixes_2021-11-05-19-28.json, common/changes/@anticrm/task-impl/task-ui-fixes_2021-11-05-19-28.json, common/changes/@anticrm/task/task-ui-fixes_2021-11-05-19-28.json, common/changes/@anticrm/ui/task-ui-fixes_2021-11-05-19-28.json, common/changes/@anticrm/workbench-impl/task-ui-fixes_2021-11-05-19-28.json, common/config/rush/command-line.json, models/dev/src/demoTask.ts, packages/ui/src/components/ActionIcon.svelte, packages/ui/src/components/CheckBox.svelte, packages/ui/src/components/CheckBoxList.svelte, packages/ui/src/components/CheckBoxWithLabel.svelte, packages/ui/src/components/Dialog.svelte, packages/ui/src/components/Header.svelte, packages/ui/src/components/Icon.svelte, packages/ui/src/components/MDRefEditor.svelte, packages/ui/src/components/Panel.svelte, packages/ui/src/components/PopupInstance.svelte, packages/ui/src/components/UserBox.svelte, packages/ui/src/types.ts, plugins/chunter-impl/src/components/ChannelProperties.svelte, plugins/task-impl/src/components/DescriptionEditor.svelte, plugins/task-impl/src/components/EditTask.svelte, plugins/task-impl/src/components/ProjectProperties.svelte, plugins/task/src/index.ts, plugins/workbench-impl/src/components/NavHeader.svelte, plugins/workbench-impl/src/components/SpaceHeader.svelte, plugins/workbench-impl/src/components/navigator/TreeElement.svelte
1. Fix Dialog Escape handling.
2. Fix checkbox and checkbox list
3.  Style description editor a bit different
4. Update Edit Task UI
5. Add more slots for Panel.svelte
=> Task UI Fixes

common/changes/@anticrm/activity-impl/activity_notifications_2021-11-11-07-46.json, common/changes/@anticrm/task-impl/activity_notifications_2021-11-11-07-46.json, plugins/activity-impl/package.json, plugins/activity-impl/src/components/TxView.svelte, plugins/task-impl/src/components/Card.svelte, plugins/task-impl/src/components/KanbanCard.svelte
=> Activity notifications

products/hr-build/package.json, products/hr-build/src/model.ts
=> Fix HR build

common/changes/@anticrm/attachment-impl/recruiting_notifications_2021-11-12-05-25.json, common/changes/@anticrm/chunter-impl/recruiting_notifications_2021-11-12-05-25.json, common/changes/@anticrm/model-recruiting/recruiting_notifications_2021-11-12-05-25.json, common/changes/@anticrm/recruiting-impl/recruiting_notifications_2021-11-12-05-25.json, common/changes/@anticrm/recruiting/recruiting_notifications_2021-11-12-05-25.json, common/changes/@anticrm/task-impl/recruiting_notifications_2021-11-12-05-25.json, models/dev/src/demoRecruiting.ts, models/recruiting/src/index.ts, plugins/attachment-impl/src/components/AttachmentsTableCell.svelte, plugins/chunter-impl/src/components/CommentsTableCell.svelte, plugins/recruiting-impl/src/components/applicants/ApplicantCard.svelte, plugins/recruiting-impl/src/components/applicants/ApplicantPresenter.svelte, plugins/recruiting-impl/src/components/applicants/CreateApplication.svelte, plugins/recruiting-impl/src/components/candidates/ApplicantsTableCell.svelte, plugins/recruiting-impl/src/components/candidates/CreateApplication.svelte, plugins/recruiting-impl/src/components/candidates/CreateCandidate.svelte, plugins/recruiting-impl/src/components/candidates/EditCandidate.svelte, plugins/recruiting-impl/src/components/vacancies/VacancyKanban.svelte, plugins/recruiting/src/index.ts, plugins/task-impl/src/components/KanbanView.svelte, utils/trello-importer/src/applicant.ts
=> Recruiting notifications

common/changes/@anticrm/chunter-impl/fix-chunter-edit-msg_2021-11-12-10-20.json, plugins/chunter-impl/src/components/Message.svelte, plugins/chunter-impl/src/components/ReferenceInput.svelte
=> Fix chunter edit messages UI
